title:             mengxn
email:             mengxn@outlook.com
description:       Know Yourself !
author:            mengxn
baseurl:           "/"
url:               "http://mengxn.github.io"

# Social Profiles
# twitter_username:  SBootstrap
github_username:   mengxn
# facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "The best time to plant a tree was 20 years ago. The second best time is now."
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`

# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "mengxn",
        href: "http://mengxn.com" 
    }
]


